import React from "react";
import { Chart } from "react-google-charts";

export const data = [
    ["Month", "Revenue", "Expenses"],
    ["January",1000,1380],
    ["February",900,1000],
    ["March",1490,1900],
    ["April",1300,1000],
    ["May",609,540],
    ["June",1290,1400],
    ["July",1300,560],
    ["August",1288,1099],
    ["September",1509,1400],
    ["October",1388,1256],
    ["November",988,1099],
    ["December",1409,1200]
];

export const options = {
  title: "Annual Finance Report",
  subtitle:"Revenue generated by scrap and resell",
  hAxis: { title: "Months", titleTextStyle: { color: "#333" } },
//   vAxis: { title: "Amount (in Rs.)", titleTextStyle: { color: "#333" } },
  vAxis: { minValue: 0 },
  chartArea: { width: "80%", height: "80%" },
  colors:['#C62828','#1565C0']
};

export default function App() {
  return (
    <Chart
      chartType="AreaChart"
      width="100%"
      height="100%"
      data={data}
      options={options}
    />
  );
}
